# mise configuration
# See: https://mise.jdx.dev/configuration.html

[tools]
adr-tools = "3.0.0"
age = "1.2.1"
bat = "0.25.0"
bottom = "0.11.2"
fd = "10.3.0"
fzf = "0.66.0"
gh = "2.81.0"
"github:cilium/cilium-cli" = "0.18.7"
gitleaks = "8.28.0"
go = "1.25.3"
gradle = "9.1.0"
helm = "3.19.0"
jq = "1.8.1"
kubectl = "1.34.1"
kubectx = "0.9.5"
kubens = "0.9.5"
lefthook = "2.0.1"
neovim = "0.11.4"
node = "22.21.0"
"npm:@anthropic-ai/claude-code" = "2.0.27"
"npm:markdownlint-cli2" = "0.18.1"
opentofu = "1.10.6"
python = "3.14.0"
ripgrep = "14.1.1"
rust = "1.90.0"
sops = "3.11.0"
starship = "1.23.0"
talosctl = "1.11.3"
task = "3.45.4"
yq = "4.48.1"

# required by lazyvim
lua = "5.4.8" # MUST be 5.1
lazygit = "0.55.1"
"github:luarocks/luarocks" = "3.12.2"
"cargo:tree-sitter-cli" = "0.25.10"

[settings]
experimental = true
