# mise configuration
# See: https://mise.jdx.dev/configuration.html

[tools]
age = "1.2.1"
bat = "0.25.0"
bottom = "0.11.2"
fd = "10.3.0"
fzf = "0.66.0"
gh = "2.81.0"
"github:cilium/cilium-cli" = "0.18.7"
gitleaks = "8.28.0"
go = "1.25.3"
gradle = "latest"
helm = "3.19.0"
jq = "1.8.1"
kubectl = "1.34.1"
kubectx = "0.9.5"
kubens = "0.9.5"
lefthook = "2.0.1"
neovim = "latest"
node = "22.21.0"
opentofu = "1.10.6"
python = "3.14.0"
ripgrep = "14.1.1"
talosctl = "1.11.3"
yq = "4.48.1"

# required by lazyvim
lua = "5.4.8" # MUST be 5.1
lazygit = "0.55.1"
"github:luarocks/luarocks" = "3.12.2"
usage = "latest"
rg = "latest"

[settings]
experimental = true
